# Generated by Django 2.2.3 on 2019-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('race', models.TextField(blank=True, db_column='Race', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('dept', models.TextField(blank=True, db_column='Dept', null=True)),
                ('block', models.TextField(blank=True, db_column='Block', null=True)),
                ('rate', models.IntegerField(blank=True, db_column='Rate', null=True)),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geography', models.TextField(blank=True, db_column='Geography', null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('median_income', models.IntegerField(blank=True, db_column='Median_Income', null=True)),
                ('median_rent', models.IntegerField(blank=True, db_column='Median_rent', null=True)),
                ('estimate_total_field', models.IntegerField(blank=True, db_column='Estimate..Total.', null=True)),
                ('no_schooling', models.IntegerField(blank=True, db_column='No_schooling', null=True)),
                ('nursery_school', models.IntegerField(blank=True, db_column='Nursery_school', null=True)),
                ('kindergarten', models.IntegerField(blank=True, db_column='Kindergarten', null=True)),
                ('x1st_grade', models.IntegerField(blank=True, db_column='X1st_grade', null=True)),
                ('x2nd_grade', models.IntegerField(blank=True, db_column='X2nd.grade', null=True)),
                ('x3rd_grade', models.IntegerField(blank=True, db_column='X3rd.grade', null=True)),
                ('x4th_grade', models.IntegerField(blank=True, db_column='X4th.grade', null=True)),
                ('x5th_grade', models.IntegerField(blank=True, db_column='X5th.grade', null=True)),
                ('x6th_grade', models.IntegerField(blank=True, db_column='X6th.grade', null=True)),
                ('x7th_grade', models.IntegerField(blank=True, db_column='X7th.grade', null=True)),
                ('x8th_grade', models.IntegerField(blank=True, db_column='X8th.grade', null=True)),
                ('x9th_grade', models.IntegerField(blank=True, db_column='X9th.grade', null=True)),
                ('x10th_grade', models.IntegerField(blank=True, db_column='X10th.grade', null=True)),
                ('x11th_grade', models.IntegerField(blank=True, db_column='X11th.grade', null=True)),
                ('x12th_grade_no_diploma', models.IntegerField(blank=True, db_column='X12th.grade..no.diploma', null=True)),
                ('regular_high_school_diploma', models.IntegerField(blank=True, db_column='Regular.high.school.diploma', null=True)),
                ('ged_or_alternative_credential', models.IntegerField(blank=True, db_column='GED.or.alternative.credential', null=True)),
                ('some_college_less_than_1_year', models.IntegerField(blank=True, db_column='Some.college..less.than.1.year', null=True)),
                ('some_college_1_or_more_years_no_degree', models.IntegerField(blank=True, db_column='Some.college..1.or.more.years..no.degree', null=True)),
                ('associate_s_degree', models.IntegerField(blank=True, db_column='Associate.s.degree', null=True)),
                ('bachelor_s_degree', models.IntegerField(blank=True, db_column='Bachelor.s.degree', null=True)),
                ('master_s_degree', models.IntegerField(blank=True, db_column='Master.s.degree', null=True)),
                ('professional_school_degree', models.IntegerField(blank=True, db_column='Professional.school.degree', null=True)),
                ('doctorate_degree', models.IntegerField(blank=True, db_column='Doctorate.degree', null=True)),
            ],
            options={
                'db_table': 'socio',
                'managed': False,
            },
        ),
    ]
