# Generated by Django 2.2.3 on 2019-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='Username', max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=10)),
                ('avatar', models.FileField(db_column='Avatar', null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
