# Generated by Django 2.2.3 on 2019-07-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
