# Generated by Django 2.2.3 on 2019-07-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0002_rate_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='Username', max_length=30, null=True)),
                ('race', models.TextField(blank=True, db_column='Race', null=True)),
                ('gender', models.TextField(blank=True, db_column='Gender', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('dept', models.TextField(blank=True, db_column='Dept', null=True)),
                ('block', models.TextField(blank=True, db_column='Block', null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
