# Generated by Django 2.2.3 on 2019-07-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('race', models.CharField(max_length=20)),
                ('geoid', models.BigIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': False,
            },
        ),
    ]
