# Generated by Django 2.2.3 on 2019-07-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0006_auto_20190724_1129'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentdb',
            table='commentdb',
        ),
    ]
