# Generated by Django 2.2.3 on 2019-07-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanager', '0007_auto_20190724_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
